### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by phaistonian** [phaistonian/Chrome-Notepad#13]
Here's something you guys could answer :)

I am referencing Amin to this ticket.

> Hello,
> 
> I'm currently learning javascript and decided to practice with google chrome extensions. I'm making a notepad extension, similar to yours in the Chrome Web Store. I am not planning on making mine public, however. I just want the learning experience. I ran into some expected trouble with the extension, as I am a novice programmer. I was hoping you could help me answer this question: How do I keep the extension from erasing text every time the window closes, and how do I make it save within the extension so that even if the browser is closed the text will remain? 
> 
> 
> 
> Thank you so much
> 
> Amin
>

**Comment by gs-akhan** [comment]
Hi Amin, 
Glad to hear you are trying it out. Alright, let me put it down for you. Whenever chrome extension is closed and reopened it looses all data associated to it. Every execution is new context and hold nothing from its previous state. 

To solve this problem, you need to store the data that you are dealing with at some place. There are some options you can try. 
1. Localstorage (Html5 localstorage, this is dedicated to your extension and no one else can delete or override it. )
2. IndexedDB : In memory database like API what allows you to store stuff. 
3. Bookmarks : browser bookmarks can also be used to store notes.

Every time extension loads, you need to load the data from the location it is stored at, and then render it to the user. Also store it back at same place on edit.

I hope that helps. 
Thanks
