### ISSUE TITLE
Fix related to character encoding

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#14]
Hi, 
We have major issue regarding encoding. Have fixed it.

@phaistonian 
please need a patch ASAP.

Thanks.

**Comment by phaistonian** [comment]
Done :)

**Comment by gs-akhan** [comment]
Thank you Sir. You are a hero .. :)

**Comment by phaistonian** [comment]
Not even close:)

**Comment by gs-akhan** [comment]
You uploaded to store ? Does it take time to reflect new version ?

**Comment by phaistonian** [comment]
Yes. 

I think not, probably an hour.
