### ISSUE TITLE
Sneak peak : Upcoming Release

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#15]
1. CSS improvements to recycle bin 
2. Settings popup 
3. Download/Export notes. 
4. Reordering (Not sure, but will try)

![recycle bin 1](https://cloud.githubusercontent.com/assets/5646166/23878917/18163950-0870-11e7-9c71-2b8e7209a62c.jpg)
![notepad-settings](https://cloud.githubusercontent.com/assets/5646166/23878926/254743a8-0870-11e7-9c82-4850487acead.jpg)

**Comment by phaistonian** [comment]
Looks really good :)
