### ISSUE TITLE
RFI

### ISSUE THREAD

**Issue by phaistonian** [phaistonian/Chrome-Notepad#16]
Here's an email from Lairu.

> Hey, I checked your extensions on chrome. I am a final year student of software engineering and i am doing notepad extension as my final year project.Is there any documentations or pdf which can help me to make my report ?
> 
> help me if u can :)  thanks !

**Comment by phaistonian** [comment]
I sent him the link to this issue  :)

**Comment by gs-akhan** [comment]
Hi, Liru. 
We don;t have any PDF or documentation. If you have specific questions about design, implementation or approach. We can certainly help you. 

Thanks

**Comment by lahirump** [comment]
Thanks, Can You send me some documentations to get an idea. :)
