### ISSUE TITLE
Drop in users

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#17]
Hi, 
I have seen drop in users since 5 days 
it had reached 95K users and now 78K. Anyway can we know the reason or count of uninstalls perday from dashboard ?

@phaistonian 
Thanks

**Comment by phaistonian** [comment]
Hey.

Sorry for the delay.

Here's the graph:

![image](https://cloud.githubusercontent.com/assets/796530/24143220/a8376f9c-0e31-11e7-8274-b62346d0c702.png)

**Comment by gs-akhan** [comment]
Nice.. So there is not much uninstallation, It might be Google updates the users with active users. 
So we are good ..

Thanks @phaistonian
