### ISSUE TITLE
Milestone 1,000,000 Page View

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#18]
Woooww !! Cannot believe it. We have 1 million page views in 3 months now. Also ~50K Notes created. 
![screen shot 2017-04-26 at 11 34 23 pm](https://cloud.githubusercontent.com/assets/5646166/25449383/3e52d89a-2ad9-11e7-80d0-57e03b183e06.png)

![screen shot 2017-04-26 at 11 34 54 pm](https://cloud.githubusercontent.com/assets/5646166/25449394/442c788e-2ad9-11e7-9d4a-6b535556e00f.png)

@phaistonian  @gs-rbarman 
Have a look.

**Comment by phaistonian** [comment]
Wow!

That is indeed awesome!

**Comment by gs-rbarman** [comment]
Amazing stats!!
