### ISSUE TITLE
New version ready.. 

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#19]
Features 
1. Reordering 

@phaistonian  please publish ..
Also please make textual changes on description ..

New features:
- New Looks,
- Multiple notes features
- Search
- Deleting
- Auto Sync with bookmarks.
- Reordering 
People involved in this project, are :
- Azharuddin @azharuddin31, azhar.mw@gmail.com (Development)
- Prashanthi Mendu mendu.prashanthi@gmail.com (Design and UX)
- Rajdeep Barman @gs-rbarman (Development)

Thanks  :)

**Comment by phaistonian** [comment]
Done :)
