### ISSUE TITLE
Couple of questions

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#2]
Hi, I just needed new clarifcations on purpose of files. 

1. Is `core.chrome.js` written by you ? for syncing ? If not I can remove it and use standard chrome bookmark syncing. 
2. Can I add features of creating folders ?
3. Can I Make it sexy looking with UI coloring/paddings etc yet keeping it simple to use?

Thanks

**Comment by phaistonian** [comment]
Hey,

sorry for being late.


1. Yes. Please, remove it or do whatever you want.
2. Sure!
3. Sure :)

thank you
