### ISSUE TITLE
Please add barmanrajdeep to this repo

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#20]
Hi @phaistonian ,
Please add barmanrajdeep as a contributor. 

Thanks

**Comment by phaistonian** [comment]
Where at ?:)

In the README @ Dashboard?

**Comment by gs-akhan** [comment]
to the repository. He is he real dude who finds bugs and fixes them .

He works with me .. we can trust him ..
Hehe

**Comment by phaistonian** [comment]
Done :)
