### ISSUE TITLE
V5.4 Ready to be Shipped. 

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#24]
Hi @phaistonian  
Please go ahead with the release. New features Added : 
1. Code Refactor 
2. Ability to Print 
3. Ability To download.
4. Link to Facebook fan page 
5. CSS improvements. 

Huge thanks to @barmanrajdeep  and @gs-avaddepalli for their massive contributions. 

What would be also great if we can add some banners to the extension page. 

Thanks & Cheers.....

**Comment by phaistonian** [comment]
Should be done.

Not sure what you mean by "banners", but I am guessing this is about adding screenshots.

Feel free to send me anything you want up there and I will do it.

Great work everyone.

**Comment by gs-akhan** [comment]
Yes, I meant some screenshots and pro banners.  
Thanks @phaistonian for the release.

**Comment by phaistonian** [comment]
Send me anything and I will upload them :)
