### ISSUE TITLE
Version 6.0.0 Ready.

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#26]
@phaistonian greetings. 
Please release Version 6.0.0 with rich text capabilities added. 

In Read me of the extension please replace the contributors part to this. We have a new contributor, Viswadeepthi Rejinthala - she added a beautiful rich text editor to the notepad. 

- Azharuddin @azharuddin31, azhar.mw@gmail.com (Development)
- Prashanthi Mendu @MenduPrashanthi (Design and UX)
- Rajdeep Barman @gs-rbarman (Development)
- Viswadeepthi Rejinthala, vishwadeepthi.r@gmail.com (Development)

Thank you very very much .. :))

**Comment by phaistonian** [comment]
Should be done :)

**Comment by gs-akhan** [comment]
Thanks. and finally the banner needs to be changed too 
<img width="801" alt="Screenshot 2019-04-02 at 11 01 19 AM" src="https://user-images.githubusercontent.com/5646166/55378534-f8117780-5536-11e9-99c7-97dfdad35191.png">

**Comment by phaistonian** [comment]
Should also be done :)

**Comment by gs-akhan** [comment]
@phaistonian need one more release.. 6.0.2
Tiny bug fix. :) 
Thanks

**Comment by phaistonian** [comment]
Done :)
