### ISSUE TITLE
Sneak peak. !! What's coming next ?

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#3]
Hi, Features Implemented are :
1. New Looks,
2. Multiple notes features
3. Search
4. Deleting 
5. Auto Sync with bookmarks. 
6. Google Analytics for tracking usage.

video link : [Video Link](http://sendvid.com/hh40753m)

**Comment by gs-akhan** [comment]
Hi, 
if you can please add me as group publisher to chrome plugin dashboard. I will update Icons, Banners, text and also take care of publishing and bug fixes..
 
:)
Thanks

**Comment by phaistonian** [comment]
I am not really sure how it's done.

Could you please guide me through?

**Comment by gs-akhan** [comment]
Sure, I will check my self how it is done. and share a video with u . Shortly.

**Comment by gs-akhan** [comment]
Hi, here it goes 
https://developer.chrome.com/webstore/publish#set-up-group-publishing
you have my email address at your gmail. I have sent you there just now.

**Comment by gs-akhan** [comment]
Did it help ?

**Comment by gs-akhan** [comment]
This is the to point tutorial. 
https://blog.chromium.org/2013/08/group-based-publishing-in-chrome-web.html

**Comment by phaistonian** [comment]
Hey.

Please excuse my delayed response; things got pretty hectic today.

There are a couple issues, I am afraid:

+ I have all sorts of extensions bound to my account, one of which is one used for our company.
+ Undoing the binding is not an option.

I am sure you understand my concerns.

Any other way we can go around it?

ps: I really like what you did with Notepad.

**Comment by gs-akhan** [comment]
Hi, no worries for delay. 
There is one way we could do this.  You can transfer owner ship of this extension to your another gmail account and then add me to group publishing. 

https://support.google.com/chrome_webstore/contact/dev_account_transfer

If that doesn't work. you will have to publish every time we have a change. :)

**Comment by phaistonian** [comment]
Let’s try the “publish when needed” approach for now and we take it from there - yes?:)

Also, your work has to be mentioned in the description so fee free to provide a new description with credits to you in there:)

—
George Papadakis
@phaistonian

**Comment by gs-akhan** [comment]
Sure, I will send u desciption please publish after that.
Thank you for ur time
MOn Tue, 31 Jan 2017 at 12:18 AM, George E. Papadakis <

**Comment by gs-akhan** [comment]
Hi, 
Here are the contributors docs 
1. George Papadakis @phaistonian (Development)
2. Azharuddin @azharuddin31, azhar.mw@gmail.com (Development)
3. Prashanthi Mendu @MenduPrashanthi (Design and UX)

Thanks, Please publish it. May the force be with you.. .. :)

**Comment by gs-akhan** [comment]
Also, please mention the plugin is totally "ad free", and also Update screen shot. 

I will updates once a week on Friday, so that you don;t feel burdened . :)

![screen shot 2017-01-31 at 1 36 51 am](https://cloud.githubusercontent.com/assets/5646166/22439488/d0b57854-e755-11e6-9ba3-6d78e1d63fe2.png)

**Comment by gs-akhan** [comment]
One more image, this is better, it has a dropdown like view. 
![screen shot 2017-01-31 at 1 39 53 am](https://cloud.githubusercontent.com/assets/5646166/22439586/3c1ed216-e756-11e6-9a77-0088d8bcd719.png)

**Comment by gs-akhan** [comment]
This one is better. It has dropdown like look..
![screen shot 2017-01-31 at 1 44 55 am](https://cloud.githubusercontent.com/assets/5646166/22439763/ec32dd50-e756-11e6-9c60-1931795836f5.png)

**Comment by phaistonian** [comment]
I had to upload the new version in a hurry because my son wanted some daddy time :)

Hopefully it did the trick. 

If not, I will check again tomorrow. 

Thank you.

**Comment by gs-akhan** [comment]
Thank you. :)
