### ISSUE TITLE
Please release minor version

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#32]
Hi, @phaistonian 
Changeset. - Added a covid-19 help text. 
![Screenshot 2020-04-03 at 10 59 27 AM](https://user-images.githubusercontent.com/5646166/78327330-30a8be80-759a-11ea-8184-6285779911c6.png)

Please release 
thanks

**Comment by gs-akhan** [comment]
@phaistonian

**Comment by phaistonian** [comment]
On it.

Sorry for lagging.

**Comment by phaistonian** [comment]
It's published - but it might take a while to be live.

**Comment by phaistonian** [comment]
![image](https://user-images.githubusercontent.com/796530/79034525-50a23880-7bbf-11ea-95be-246d5eef0d02.png)

I am afraid it got rejected.

Narrowing down the permissions to what's totally needed will probably do it.

**Comment by gs-akhan** [comment]
Sure I will change the persmissions.

**Comment by gs-akhan** [comment]
I have removed tabs permission, can you retry ?
Thanks

**Comment by phaistonian** [comment]
Done :)
