### ISSUE TITLE
Please release new version at earliest. 

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#39]
@phaistonian  #SOS
We found a terrible blocker and want to release new version.

Thanks

**Comment by phaistonian** [comment]
Hey.

Pushed a new version — it's under review for now.

It won't take long, hopefully.

**Comment by rustwolf** [comment]
Thank you Sir.  Also I have given a temp fix. it might at worst case require you to do one more if needed.

Sorry for inconvenience :)))

**Comment by gs-akhan** [comment]
Thank you sir.
Also I have given a temp fix since we got infinite number of messages from users..

In worst case we might need one more fix if it doesnt fixes the issue.. Thank you in advance., :))

**Comment by phaistonian** [comment]
Sure - anytime :-)
