### ISSUE TITLE
Critical Bug Fixes

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#4]
Hi, 
After updating we had two issues. 
1. Support for Chinese and European characters. 
2. Word Wrapping on text area. 

Both of them are fixed. If you get little free time over lunch please publish. I have bumped version. Just pull and upload. 

Thanks :)

**Comment by gs-akhan** [comment]
@phaistonian

**Comment by phaistonian** [comment]
Awesome.

I will do it a bit later - on my way back from work now.

**Comment by phaistonian** [comment]
Actually,

I got some moments so I did update.

Should be fine now.

Thank you:)
