### ISSUE TITLE
5.2 Ready 

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#5]
Issues Fixed :
1. Focus the note when opening, navigating and creating new note. 
2. Aligning issues 
3. Typo in Options page. 
4. Offline Flag added. So Chrome store can filter it based on "offline filter" 

Whenever you are free over weekend please publish. No hurries on this. :))  I have

Thanks

**Comment by phaistonian** [comment]
Done :)

I created a little script to bundle and zip and all so it's super-easy now to publish.

Also, I just got a mail about notepad - opening an issue about so you can take a look if you want :)
