### ISSUE TITLE
Notepad chrome extension inquiry

### ISSUE THREAD

**Issue by phaistonian** [phaistonian/Chrome-Notepad#6]
This is what I got today (from James).

```
Hi.

So all of my notes are gone.

 I still have the synced bookmark, but I can only see like 10% of what I had amongst the coding.

I tried re-installing. But new notes don't even save at all.

Please help... this is devastating. I had really important notes in there.

Thanks.
```

**Comment by gs-akhan** [comment]
Ohh this is sad. 
I have had tested all upgrade scenarios. and all backup mechanism is in place. we now write to new folder instead of Bsync. 
Anyways I will have a look.

**Comment by gs-akhan** [comment]
the plugin is working fine for you right ?

**Comment by gs-akhan** [comment]
I will add exception tracking using Google Analytics. We will have better insights using this. Will publish it tomorrow.

**Comment by jam35r** [comment]
Hey, James here. Will do pretty much anything to help out.

**Comment by gs-akhan** [comment]
@jam35r  I am so sorry for you notes getting lost. Did you try to recover from Bsync Folder ?
Thanks

**Comment by jam35r** [comment]
@gs-akhan Yes I did. Like I mentioned before, I only see 10% of the notes between the coding (where it says "url") so I'm pretty sure that my note are lost, unless you can open the link and then there's more? I dunno.

**Comment by gs-akhan** [comment]
:( The URL is where all text was stored, Also in the local storage of the browser.  
But I had tested all cases before pushing uprade, I dont know how they disappeared.

**Comment by jam35r** [comment]
Ah. So I'll take that as a lost cause. I'll get over it eventually. You guys probably know already, but it doesn't seem like it was just me that it happened to (if you check the support page of the extension).

**Comment by gs-akhan** [comment]
@jam35r Also Update when to 15000 users till date. Only 3-4 reported a loss.  I tested with my friends machines too, who used this plugin. 
Anyways. Will be 1000 times more sure before upgrading anything. 
I hope your important stuff is recoverable by other means.

**Comment by gs-akhan** [comment]
@jam35r  Did you try to delete bookmarks anytime back ?

**Comment by jam35r** [comment]
I dunno if it'll help, but I'll just mention anyway. I can see my most recent notes in the bookmark (like maybe, a month of new notes). But I've been using this extension for a very long time so I had a lot of notes. As it gets older they start to disappear. But sporadically, and then completely gone.

For example if "O" were the notes that were recoverable and "X" are the ones that disappeared. It looks like something like this. (Newer notes at top, older notes at bottom).

O
O
O
O
O
O
O
O
O
O
X
O
O
X
O
O
X
O
X
O
X
X
X
X
X
O
X
X
X
X
X
O
X
X
X
X
X
X
X
X
and then anything older than here is just gone.

**Comment by jam35r** [comment]
@gs-akhan I did not try to delete bookmarks, no. But the bsync folder was in my "mobile bookmarks" if that makes any difference...

**Comment by gs-akhan** [comment]
@jam35r the length matters. The Bookmark URL can store limited text. It would automatically truncate text if it exceeds. Also earlier sync logic wasn't working well. 

Btw, Are you able to use the notepad now ?

**Comment by gs-akhan** [comment]
With this update, you have ability to add multiple notes and the sync logic is pretty solid.  I hope there would not be issues like this going forward.
Also will add export notes functionality to export them as text files.
