### ISSUE TITLE
Upcoming Release Items

### ISSUE THREAD

**Issue by gs-akhan** [phaistonian/Chrome-Notepad#7]
1. Confirmation before deleting notes or recycle bin functionality. 
2. Resize Window options. 
3.  Google Analytics for capturing run-time errors. 

Its not ready yet. Will update once its done.

**Comment by gs-akhan** [comment]
@phaistonian  
Release ready. Version 5.3. Bump the version and make the release. Also add @gs-rbarman  as contributor for his valuable contribution towards feature of recycle bin.

Rajdeep Barman - <barman.rajdeep@gmail.com> (Development)

Also Add this Banner on the showcase area. 

![screen shot 2017-02-19 at 11 00 43 pm](https://cloud.githubusercontent.com/assets/5646166/23104647/15fa2e30-f6f8-11e6-9d99-9b22d4f4fee9.png)

When ever you find some free time make a release.  :) 👍 
Thanks.

**Comment by phaistonian** [comment]
Hey all.

I just uploaded the new released and added Rajdeep to the credits info.

Thing is, for the new screenshot/material to be uploaded, it has to be of certain size (1200 x 800).

Do you have it in vector format? Or, can you send me the icon so I can do it myself?:)

**Comment by gs-akhan** [comment]
Thank you. I will send you the SVG format.

**Comment by gs-akhan** [comment]
ohh nooo I deleted the sketch project. I only have the Icon in SVG.

**Comment by gs-akhan** [comment]
Thank you very much. One small error. 
- Prashanthi Mendu @MenduPrashanthi (Design and UX)
This contributors name appears two times in chrome store. 

Thanks

**Comment by phaistonian** [comment]
oops.

Fixed.

ps: Seeing [this](https://www.producthunt.com/posts/notepin-2) made me thinking that this (all new) version of Chrome Notepad could be in there as well.

**Comment by gs-akhan** [comment]
Wooow ...  We deserve to be on product hunt too ..

**Comment by gs-akhan** [comment]
I will setup Facebook fan page and Twitter Bot..  We will soon have a brand - Notepad Brand
